before:
  hooks:
    - bash -c "cd frontend && yarn && yarn run webpack --mode production"
builds:
  - id: default 
    env:
    - CGO_ENABLED=1
    main: ./cmd/webmentiond
    goos:
      - linux
    goarch:
      - amd64
archives:
  - wrap_in_directory: true
    builds:
      - default
    format: zip
    files:
      - frontend/css/*
      - frontend/dist/*
      - frontend/index.html
      - frontend/demo.html
      - pkg/server/migrations/*
blobs:
  - provider: s3
    endpoint: https://ams3.digitaloceanspaces.com
    bucket: zerokspot-media
    folder: releases/webmentiond/{{ .Version }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Commit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
