name: Tag

on:
  push:
    tags:
      - "v*"

jobs:
  "tag-main":
    name: "Tag"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
    - name: Log into DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Run dagger
      env:
        GIT_COMMIT_ID: ${{ github.sha }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        RELEASE_VERSION: ${{ github.ref_name }}
        IMAGE_NAME: "zerok/webmentiond"
      run: go run ./ci --build --publish
